version: '2'

services:

#########################
#  PostgreSQL Database  #
#########################

    postgres:
        image: postgres:9
        ports:
         - "5432:5432"        
        environment:
         -  POSTGRES_PASSWORD=syncope
         -  POSTGRES_USER=syncope
         -  POSTGRES_DB=syncope
#        volumes:
#         - ./db-init-scripts/:/docker-entrypoint-initdb.d/:ro
#         - postgresql_data:/var/lib/postgresql/data
#         - /etc/timezone:/etc/timezone:ro

#########################
#  Apache Syncope Core  #
#########################

    syncope-core:
      image: syncope-core:2.0.7
      ports:
        - "8080:8080"
      volumes:
        - /var/log/apache-syncope:/var/log/apache-syncope:rw
      depends_on:
        -  postgres      

############################
#  Apache Syncope Console  #
############################

    syncope-console:
      image:  syncope-console:2.0.7
      ports:
        - "9080:8080"
      volumes:
        - /var/log/apache-syncope:/var/log/apache-syncope:rw
      depends_on:
        - syncope-core

###############################
#  Apache Syncope Enduser UI  #
###############################

    syncope-enduser:
      image:  syncope-enduser:2.0.7
      ports:
        - "7080:8080"
      volumes:
        - /var/log/apache-syncope:/var/log/apache-syncope:rw
      depends_on:
        - syncope-core
