apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.6.0 (e4adfef)
  creationTimestamp: null
  labels:
    io.kompose.service: syncope-console
  name: syncope-console
spec:
#  clusterIP: None
  type: NodePort
  ports:
  - name: headless
    port: 55555
    targetPort: 8080
  selector:
    io.kompose.service: syncope-console
status:
  loadBalancer: {}
